name: Flutter CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/devops_project-action@v2
        with:
          flutter-version: '3.10.0'

      - name: Upgrade Flutter
        run: flutter upgrade
        working-directory: ./devops_project

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./devops_project  

      - name: Run Flutter doctor
        run: flutter doctor
        working-directory: ./devops_project

     #- name: Run tests
     #  run: flutter test
     # working-directory: ./devops_project  

      #- name: Build the app
       # run: flutter build apk --release
       # working-directory: ./devops_project  

      - name: Build the app for web
        run: flutter build web --release
        working-directory: ./devops_project

      - name: Clear Flutter cache
        run: flutter doctor --android-licenses
        working-directory: ./devops_project  

      - name: Debug Flutter version
        run: flutter --version
        working-directory: ./devops_project
