name: devops_project CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up devops_project
        uses: subosito/devops_project-action@v2
        with:
          devops_project-version: '3.10.0'

      - name: Upgrade devops_project
        run: devops_project upgrade
        working-directory: ./devops_project

      - name: Install dependencies
        run: devops_project pub get
        working-directory: ./devops_project  

      - name: Run devops_project doctor
        run: devops_project doctor
        working-directory: ./devops_project

     #- name: Run tests
     #  run: devops_project test
     # working-directory: ./devops_project  

      - name: Build the app
        run: devops_project build apk --release
        working-directory: ./devops_project  

      - name: Clear devops_project cache
        run: devops_project doctor --android-licenses
        working-directory: ./devops_project  

      - name: Debug devops_project version
        run: devops_project --version
        working-directory: ./devops_project
